- name: Create Dockerfile and copy to docker host
  template:
    src: Dockerfile.js
    dest: /home/{{ admin }}/Dockerfile

- name: WebTelnet image
  community.docker.docker_image_build:
    name: ndsr/webtelnet:v1
    path: /home/{{ admin }}
    dockerfile: Dockerfile

- name: Copy files for backend
  ansible.builtin.copy:
    src: ../../../../ndsr-app/api
    dest: /home/{{ admin }}

- name: NDSR-APP Backend image
  community.docker.docker_image_build:
    name: ndsr/backend:v1
    path: /home/{{ admin }}/api/
    dockerfile: Dockerfile_backend

- name: NDSR-APP Frontend image
  community.docker.docker_image_build:
    name: ndsr/frontend:v1
    path: /home/{{ admin }}/api/
    dockerfile: Dockerfile_backend