- name: Copy files for ndsr-app
  ansible.builtin.copy:
    src: ../../../../ndsr-app
    dest: /home/{{ admin }}

- name: Copy files for ndsr-app
  ansible.builtin.copy:
    src: .env.example
    dest: /home/{{ admin }}/api/.env.example

- name: Create Dockerfile Webtelnet image's and copy to docker host
  template:
    src: Dockerfile.js
    dest: /home/{{ admin }}/Dockerfile_webtelnet

- name: Copy app docker-compose file to remote host
  copy:
   src: ndsr-app.yml
   dest: /home/{{ admin }}

- name: Copy app env file to remote host
  copy:
   src: VARS-APP.env
   dest: /home/{{ admin }}

- name: Run `docker-compose APP up`
  community.docker.docker_compose_v2:
     project_src: /home/{{ admin }}
     files: ndsr-app.yml
     project_name: ndsr-app
     env_files: VARS-APP.env
  register: output

- name: Show results
  debug:
     var: output