- name: Install Plugin
  ansible.builtin.script: ./scripts/installPlugin.sh

- name: Enable the plugin
  community.docker.docker_plugin:
    plugin_name: ghcr.io/devplayer0/docker-net-dhcp:golang
    state: enable

- name: Copy docker-compose file to remote host
  copy:
   src: ndsr.yml
   dest: /home/{{ admin }}

- name: Copy docker-compose file to remote host
  copy:
   src: VARS.env
   dest: /home/{{ admin }}

- name: Download IMAGE and search image id
  ansible.builtin.script: ./scripts/downloadImage.sh "'{{ password }}' '{{ user }}'"

- name: Run `docker-compose up`
  community.docker.docker_compose_v2:
     project_src: ./
     files: ndsr.yml
     project_name: ndsr
     env_files: VARS.env
  register: output

- name: Show results
  debug:
     var: output

- name: Copy script for auto-start containers after reboot
  copy:
    src: startNdsrService.sh
    dest: /usr/bin
    owner: '{{ admin }}'
    group: '{{ admin }}'
    mode: 0775
  become: true

- name: Create start docker compose systemd service file
  template:
    src: docker_start.service.j2
    dest: /etc/systemd/system/docker_start.service
    owner: root
    group: root
    mode: 0644
  become: true
  vars:
   HOME: "/home/{{ admin }}"
  
- name: Enable docker compose service
  systemd:
    name: docker_start
    enabled: yes
    daemon_reload: yes
  become: true

- name: Setup IPTABLES for nat WEB
  ansible.builtin.script: ./scripts/setupIptablesCFK.sh
  when: "'TRASP' in inventory_hostname"

- name: Setup IPTABLES, access to CFK
  ansible.builtin.script: ./scripts/setupIptablesDH.sh
  when: "'TRASP' in inventory_hostname"