---

- name: Delete repo in resources
  lineinfile: dest=/etc/apt/sources.list
              state=absent
              regexp='buster-backports'
  become: yes

- name: Install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    update_cache: yes
    state: present
  become: yes

- name: iptables save
  shell: netfilter-persistent save
  when: "'containers' in group_names"
  become: yes

  - name: Copy script for automatically update ip address on containers
  copy:
    src: ../../../scripts/changeContainersIp.sh
    dest: /usr/bin
    owner: root
    mode: 0775
  become: true

  - name: Copy script for monitoring routes
  copy:
    src: ../../../scripts/monitorRoutes.sh
    dest: /usr/bin
    owner: root
    mode: 0775
  become: true

- name: Create monitorGw systemd service file
  template:
    src: ../templates/changeContainersIp.j2
    dest: /etc/systemd/system/monitorGw.service
    owner: root
    group: root
    mode: 0777
  become: true
  when: "'containers' in group_names"
  with_items: "{{ http_forward }}"
  
- name: Create monitorRoute systemd service file
  template:
    src: ../templates/monitorRoutes.j2
    dest: /etc/systemd/system/monitorRoute.service
    owner: root
    group: root
    mode: 0777
  become: true
  when: "'containers' in group_names"
  

- name: Enable monitorGW service
  systemd:
    name: monitorGw
    enabled: yes
    daemon_reload: yes
  become: true

- name: Enable monitorRoute service
  systemd:
    name: monitorRoute
    enabled: yes
    daemon_reload: yes
  become: true  