---

- name: Delete repo in resources
  lineinfile: dest=/etc/apt/sources.list
              state=absent
              regexp='buster-backports'
  become: yes

- name: Install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    update_cache: yes
    state: present
  become: yes

- name: iptables save
  shell: netfilter-persistent save
  when: "'containers' in group_names"
  become: yes