- 
  sname: Docker Compose Restart
  hosts: TRASP
  tasks:
    - name: Docker Compose Restart
      community.docker.docker_compose_v2:
       project_src: ./
       files: ndsr.yml
       project_name: ndsr
       env_files: VARS.env
       state: restarted
      register: output


 