- name: Docker Compose Start/UP project NDSR
  hosts: TRASP
  vars_prompt:
   - name: user
     prompt: "Enter the user to connect to ESXI"
     unsafe: true
     private: false
   - name: password
     prompt: "Enter password for the user"
     unsafe: true
     private: true
   - name: admin
     prompt: "Enter the user admin project's"
     unsafe: true
     private: false
  roles:
    - NDSR-Compose-role