---
- name: Setup DNS Resolving
  ansible.builtin.script: ./scripts/setupResolvConf.sh
  when: "'TRASP' in groups['docker_host']"
  become: yes

- name: Setup iptables for DHCP
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: '{{ item.bridge }}'
    rule_num: '1'
    action: insert
    protocol: all
    jump: ACCEPT
  become: yes
  when: "'TRASP' in groups['docker_host']"
  with_items: "{{ network_bridge }}"

- name: Create rule for MASQUERADE
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: internet
    jump: MASQUERADE
  when: "'TRASP' in groups['docker_host']"
  become: yes

- name: FORWARD rules for traffic from containers
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: 'internet'
    destination: '10.10.19.0/24'
    action: insert
    protocol: all
    jump: ACCEPT
  become: yes
  when: "'TRASP' in groups['docker_host']"

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: '{{ item }}'
    rule_num: '1'
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  when: "'TRASP' in groups['docker_host']"
  loop:
    - INPUT
    - FORWARD

- name: HTTP setup
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: internet
    protocol: tcp
    destination_port: '{{ item.port }}'
    jump: DNAT
    to_destination: '{{ item.ip }}'
  with_items: "{{ http_forward }}"
  become: yes
  when: "'TRASP' in groups['docker_host']"

- name: SSH setup
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: internet
    protocol: tcp
    destination_port: '{{ item.port }}'
    jump: DNAT
    to_destination: '{{ item.ip }}'
  with_items: "{{ ssh_forward }}"
  become: yes
  when: "'TRASP' in groups['docker_host']"

- name: VNC setup
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: internet
    protocol: tcp
    destination_port: '{{ item.port }}'
    jump: DNAT
    to_destination: '{{ item.ip }}'
  with_items: "{{ vnc_forward }}"
  become: yes
  when: "'TRASP' in groups['docker_host']"

- name: Add iptables rule for TCPMSS
  ansible.builtin.script: ./scripts/tcpmss.sh

- name: iptables save
  shell: netfilter-persistent save
  when: "'TRASP' in groups['docker_host']"
  become: yes