###создаем image для frontend
FROM node:20.13.1-alpine3.20 as builder
WORKDIR /app
COPY /home/{{ admin }}/ndsr-app .
RUN npm install && npm run build

FROM nginx
RUN rm -f /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./nginx.conf.j2 /etc/nginx/config.d/nginx.conf
CMD ["nginx", "-g", "daemon off;"]