###создаем image для Backend
FROM node:20.13.1-alpine3.20
WORKDIR /app
COPY /home/{{ admin }}/ndsr-app/api .
RUN mv ./.env.example ./.env
RUN npm install telnet-client && npm install --production
CMD [ "node", "server.js" ]
