- 
  name: Setup Docker Compose and containers
  hosts: containers
  roles:
    - SetupContainers

- 
  name: Docker Compose (RESTART)
      community.docker.docker_compose_v2:
       project_src: ./
       files: ndsr.yml
       project_name: ndsr
       env_files: VARS.env
       state: restarted