###создаем image для frontend
FROM node:20.13.1-alpine3.20 as builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM nginx
RUN rm -rf /usr/share/nginx/html
COPY --from=builder /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]