---
- name: Delete repo in resources
  lineinfile: dest=/etc/apt/sources.list
              state=absent
              regexp='buster-backports'
  become: yes

- name: Install iptables-persistent
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  become: yes
  loop:
  - iptables-persistent
  - telnet
  - firefox-esr

- name: iptables save
  shell: netfilter-persistent save
  become: yes

- name: Copy script for automatically update ip address on containers
  copy:                                                                                                                                                                                                                                    
      src: changeContainersIp.sh
      dest: /usr/bin
      owner: root
      mode: 0775
  become: true

- name: Copy script for monitoring routes
  copy:
     src: monitorRoutes.sh
     dest: /usr/bin
     owner: root
     mode: 0775
  become: true

- name: Create monitorGw systemd service file
  template:
    src: changeContainersIp.j2
    dest: /etc/systemd/system/monitorGw.service
    owner: root
    group: root
    mode: 0777
  become: true

- name: Create monitorRoute systemd service file
  template:
    src: monitorRoutes.j2
    dest: /etc/systemd/system/monitorRoute.service
    owner: root
    group: root
    mode: 0777
  become: true
  
- name: Enable&&Start monitorGW service
  systemd:
    name: monitorGw
    enabled: yes
    state: started
    daemon_reload: yes
  become: true

- name: Enable&&Start monitorRoute service
  systemd:
    name: monitorRoute
    enabled: yes
    state: started
    daemon_reload: yes
  become: true  